base:
  name:     Webzination
  owner:    Daniel Cunningham
  charset:  UTF-8
  lang:     de
  email:    dcunningham90@online.de
  

nav:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Projekte
    url: /works
  - title: Kontakt
    url: /contact